### PR TITLE
IE8/9 (XDomainRequest): throw if cross scheme

### PR DESCRIPTION
**Pull request by OliverJAsh**
/cc @janua

### CODE REVIEW

**Comment by OliverJAsh** [comment]
(Not tested)

**Comment by ded** [comment]
This is good. Perhaps we can clean up the error message to simply be `XDomainRequest: requests must be targeted to the same scheme as the hosting page.` and we can leave the URL in the source as a comment.

**Comment by OliverJAsh** [comment]
Done! I will test if you're happy with how this looks.

**Comment by ded** [comment]
looks good.

**Comment by OliverJAsh** [comment]
I had to workaround https://github.com/ded/reqwest/issues/202, but it works:

image

**Comment by janua** [comment]
This is great!
If we can see this in our console when testing it it will point us in the right direction. Currently all you see is `Access is denied` in the IE 9 console and it's very difficult to diagnose what actually happened.

**Comment by ded** [comment]
@janua are you saying that in IE9 there's no error message to a line number?

**Comment by OliverJAsh** [comment]
@janua I think he's saying that the error message isn't very helpful because it doesn't say what the error actually is caused by.

**Comment by janua** [comment]
@ded @OliverJAsh Yep, I get this.

    SCRIPT5: Access is denied.
    <current path>, line 1 character 1.

Not very helpful at all.

**Comment by OliverJAsh** [comment]
Can we merge this please? Just ran into it again!

**Pull request merged**
