### PR TITLE
Feature/isomorphic

### PR DESCRIPTION
**Pull request by ded**
Officially address #153 allowing `reqwest` to work in Node!

This does require, however, the peer dependency of `xhr2` and will need to be noted in the docs.

### CODE REVIEW

**Comment by BDiehr** [comment]
Hi ded, thanks for adding this feature, when do you think you will push out this features onto your npm module?

**Comment by ded** [comment]
@BDiehr It's been pushed and tagged at `2.0.0`

**Comment by BDiehr** [comment]
Thanks!

**Comment by BDiehr** [comment]
Hi Ded, I've had a chance to implement this, though I'm having a bit of an unexpected result.

This following code works, both on the server and client:

```
    return process.env.BROWSER
      ? request({
        url: `${SARK_URL}/status`,
        method: 'GET',
        crossOrigin: true
      })
      : request({
        url: `${SARK_URL}/status`,
        method: 'GET'
      });
```

While the following below does not (though I would expect it to be equivalent)

```
  return request({
        url: `${SARK_URL}/status`,
        method: 'GET',
        crossOrigin: process.env.BROWSER
      })
```

It appears even having the `crossOrigin` option existing in the object passed to reqwest is causing a 500 error.

The following is the error output:

```
_1 | Fri, 17 Jul 2015 20:00:31 GMT koa `rendering error`
qbpdbclient_1 | Fri, 17 Jul 2015 20:00:31 GMT koa Error: Browser does not support cross-origin requests
qbpdbclient_1 |     at xhr (/home/src/node_modules/reqwest/reqwest.js:70:19)
qbpdbclient_1 |     at Object.getRequest (/home/src/node_modules/reqwest/reqwest.js:219:35)
qbpdbclient_1 |     at Object.init (/home/src/node_modules/reqwest/reqwest.js:379:31)
qbpdbclient_1 |     at Object.Reqwest (/home/src/node_modules/reqwest/reqwest.js:249:10)
qbpdbclient_1 |     at reqwest (/home/src/node_modules/reqwest/reqwest.js:443:12)
qbpdbclient_1 |     at AuthorizationService.getStatus (/home/src/app/services/AuthorizationService.js:7:12)
qbpdbclient_1 |     at promise (/home/src/app/actions/users.js:17:10)
qbpdbclient_1 |     at new Promise (/home/src/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
qbpdbclient_1 |     at /home/src/app/utils/alt-resolver.js:30:45
qbpdbclient_1 |     at Array.map (native)
qbpdbclient_1 | Fri, 17 Jul 2015 20:00:31 GMT dev return html content
```

I realize the goal of reqwest is not to become an all encompassing isomorphic request library, do you have a recommendation on such a library? I was not able to find anything that fit the bill. I love the style in which `reqwest` uses reqwest so I still have hopes on using it but I'd love to hear your thoughts on this.

Once again thanks for taking the time to help out on this.

**Pull request merged**
